allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - undici@6.23.0 || 6.24.0 || 6.27.0
  - brace-expansion@5.0.8
overrides:
  brace-expansion@<=5.0.7: ^5.0.8
  undici@<6.23.0: ^6.23.0
  undici@<6.24.0: ^6.24.0
  undici@<6.27.0: ^6.27.0
