name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm

      - name: Install & Build
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm build

      - name: Generate Skill Icons
        id: skill-icons
        uses: ./

      - name: Print Output
        id: print-output
        run: |
          echo "[LIST]: ${{ steps.skill-icons.outputs.list }}"
          echo "[UPDATED]?: ${{ steps.skill-icons.outputs.updated }}"
          echo "[PATH]: ${{ steps.skill-icons.outputs.path }}"
